# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BabyBluetoothAppDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BabyBluetoothAppDemo
pod "RMDateSelectionViewController", "~> 2.0.3"
pod 'MJExtension'
pod 'AVOSCloud' 
end
